apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  APP_ENV: ZGV2
  APP_SECRET: ZWViMTQyOWFiMmQzMDNhZGQ2OThkYTJjY2UxMzIwNWE=
  DATABASE_URL: bXlzcWw6Ly9yb290OjEyMzQ1NkBkYXRhYmFzZS1zZXJ2aWNlL2NvbnRyb2xlLW9yY2FtZW50bz9zZXJ2ZXJWZXJzaW9uPTguMSZjaGFyc2V0PXV0ZjhtYjQ=
  JWT_PASSPHRASE: MlloMTJyIXpRdiMh
