apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config-map
data:
  APP_ENV: dev
  APP_SECRET: eeb1429ab2d303add698da2cce13205a
  DATABASE_URL: mysql://root:123456@database-service/controle-orcamento?serverVersion=8.1&charset=utf8mb4
  JWT_PASSPHRASE: 2Yh12r!zQv#!

