apiVersion: v1
kind: Pod
metadata:
  name: database
  labels:
    app: database
spec:
  containers:
    - name: database
      image: mysql:8.0
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
      env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: database-secrets
            key: MYSQL_ROOT_PASSWORD
      ports:
        -  containerPort: 3306